name: "Setup Terragrunt"
description: "Install Terraform and Terragrunt"

inputs:
  terraform_version:
    description: "Terraform version"
    required: false
    default: "1.9.8"
  terragrunt_version:
    description: "Terragrunt version"
    required: false
    default: "0.72.6"

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}
        terraform_wrapper: false

    - name: Install Terragrunt
      shell: bash
      run: |
        ARCH="$(uname -m)"
        case "${ARCH}" in
          x86_64)  ARCH="amd64" ;;
          aarch64) ARCH="arm64" ;;
        esac
        curl -sL "https://github.com/gruntwork-io/terragrunt/releases/download/v${{ inputs.terragrunt_version }}/terragrunt_linux_${ARCH}" \
          -o /usr/local/bin/terragrunt
        chmod +x /usr/local/bin/terragrunt
        terragrunt --version
